#!/bin/bash

PROGRAM=hello_world.fcgi

down()
{
	kill $1
	kill $2
	wait $1
	wait $2
	echo "done"
	exit
}

./hello_world.fcgi -c config.txt &
SERVER=$!

/usr/sbin/lighttpd -D -f light.conf &
PROCESS=$!

trap "echo signal... ; down $SERVER  $PROCESS " SIGHUP SIGINT SIGTERM

echo "Press any key to exit"
read
down $SERVER  $PROCESS


