/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_CPPCMS_API_H
#define PHP_CPPCMS_API_H

extern zend_module_entry cppcms_api_module_entry;
#define phpext_cppcms_api_ptr &cppcms_api_module_entry

#ifdef PHP_WIN32
# define PHP_CPPCMS_API_API __declspec(dllexport)
#else
# define PHP_CPPCMS_API_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(cppcms_api);
PHP_MSHUTDOWN_FUNCTION(cppcms_api);
PHP_RINIT_FUNCTION(cppcms_api);
PHP_RSHUTDOWN_FUNCTION(cppcms_api);
PHP_MINFO_FUNCTION(cppcms_api);

ZEND_NAMED_FUNCTION(_wrap_new_CppCMSAPIPool);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPIPool_error);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPIPool_error_message);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPIPool_error_clear);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPIPool_init);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPIPool_init_from_json);
ZEND_NAMED_FUNCTION(_wrap_new_CppCMSAPISession);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_error);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_error_message);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_error_clear);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_init);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_clear);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_is_set);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_erase);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_exposed);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_exposed);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_first_key);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_next_key);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_csrf_token);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_binary_as_hex);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_binary_as_hex);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_binary_len);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_reset_session);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_default_age);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_age);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_age);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_default_expiration);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_expiration);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_expiration);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_on_server);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_on_server);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_session_cookie_name);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_load);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_save);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_cookie_first);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_cookie_next);
ZEND_NAMED_FUNCTION(_wrap_new_CppCMSAPICookie);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_header);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_header_content);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_name);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_value);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_path);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_domain);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_max_age_defined);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_max_age);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_expires_defined);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_expires);
ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_is_secure);
#endif /* PHP_CPPCMS_API_H */
