LIBS=-lcppcms


all: clean hello-tmpl.fcgi view.so

view.cpp: first.tmpl
	cppcms_tmpl_cc first.tmpl -o view.cpp

view.so: data.h view.cpp
	g++ -shared -fPIC view.cpp -o view.so ${LIBS}

hello-tmpl.fcgi: hello-tmpl.cpp data.h
	g++ -Wall -export-dynamic hello-tmpl.cpp -o hello-tmpl.fcgi ${LIBS}

clean:
	rm -f *.fcgi *.exe view.cpp *.so
