/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGPHP
#define SWIGPHP
#endif

#define SWIG_PREFIX ""
#define SWIG_PREFIX_LEN 0
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

/* -----------------------------------------------------------------------------
 * swigrun.swg
 *
 * This file contains generic C API SWIG runtime support for pointer
 * type checking.
 * ----------------------------------------------------------------------------- */

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "4"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
# define SWIG_QUOTE_STRING(x) #x
# define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
# define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
# define SWIG_TYPE_TABLE_NAME
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the SWIG runtime code.
  In 99.9% of the cases, SWIG just needs to declare them as 'static'.

  But only do this if strictly necessary, ie, if you have problems
  with your compiler or suchlike.
*/

#ifndef SWIGRUNTIME
# define SWIGRUNTIME SWIGINTERN
#endif

#ifndef SWIGRUNTIMEINLINE
# define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

/*  Generic buffer size */
#ifndef SWIG_BUFFER_SIZE
# define SWIG_BUFFER_SIZE 1024
#endif

/* Flags for pointer conversions */
#define SWIG_POINTER_DISOWN        0x1
#define SWIG_CAST_NEW_MEMORY       0x2

/* Flags for new pointer objects */
#define SWIG_POINTER_OWN           0x1


/*
   Flags/methods for returning states.

   The SWIG conversion methods, as ConvertPtr, return an integer
   that tells if the conversion was successful or not. And if not,
   an error code can be returned (see swigerrors.swg for the codes).

   Use the following macros/flags to set or process the returning
   states.

   In old versions of SWIG, code such as the following was usually written:

     if (SWIG_ConvertPtr(obj,vptr,ty.flags) != -1) {
       // success code
     } else {
       //fail code
     }

   Now you can be more explicit:

    int res = SWIG_ConvertPtr(obj,vptr,ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
    } else {
      // fail code
    }

   which is the same really, but now you can also do

    Type *ptr;
    int res = SWIG_ConvertPtr(obj,(void **)(&ptr),ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
      if (SWIG_IsNewObj(res) {
        ...
	delete *ptr;
      } else {
        ...
      }
    } else {
      // fail code
    }

   I.e., now SWIG_ConvertPtr can return new objects and you can
   identify the case and take care of the deallocation. Of course that
   also requires SWIG_ConvertPtr to return new result values, such as

      int SWIG_ConvertPtr(obj, ptr,...) {
        if (<obj is ok>) {
          if (<need new object>) {
            *ptr = <ptr to new allocated object>;
            return SWIG_NEWOBJ;
          } else {
            *ptr = <ptr to old object>;
            return SWIG_OLDOBJ;
          }
        } else {
          return SWIG_BADOBJ;
        }
      }

   Of course, returning the plain '0(success)/-1(fail)' still works, but you can be
   more explicit by returning SWIG_BADOBJ, SWIG_ERROR or any of the
   SWIG errors code.

   Finally, if the SWIG_CASTRANK_MODE is enabled, the result code
   allows to return the 'cast rank', for example, if you have this

       int food(double)
       int fooi(int);

   and you call

      food(1)   // cast rank '1'  (1 -> 1.0)
      fooi(1)   // cast rank '0'

   just use the SWIG_AddCast()/SWIG_CheckState()
*/

#define SWIG_OK                    (0)
#define SWIG_ERROR                 (-1)
#define SWIG_IsOK(r)               (r >= 0)
#define SWIG_ArgError(r)           ((r != SWIG_ERROR) ? r : SWIG_TypeError)

/* The CastRankLimit says how many bits are used for the cast rank */
#define SWIG_CASTRANKLIMIT         (1 << 8)
/* The NewMask denotes the object was created (using new/malloc) */
#define SWIG_NEWOBJMASK            (SWIG_CASTRANKLIMIT  << 1)
/* The TmpMask is for in/out typemaps that use temporal objects */
#define SWIG_TMPOBJMASK            (SWIG_NEWOBJMASK << 1)
/* Simple returning values */
#define SWIG_BADOBJ                (SWIG_ERROR)
#define SWIG_OLDOBJ                (SWIG_OK)
#define SWIG_NEWOBJ                (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ                (SWIG_OK | SWIG_TMPOBJMASK)
/* Check, add and del mask methods */
#define SWIG_AddNewMask(r)         (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r)           (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r)         (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r)           (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))

/* Cast-Rank Mode */
#if defined(SWIG_CASTRANK_MODE)
#  ifndef SWIG_TypeRank
#    define SWIG_TypeRank             unsigned long
#  endif
#  ifndef SWIG_MAXCASTRANK            /* Default cast allowed */
#    define SWIG_MAXCASTRANK          (2)
#  endif
#  define SWIG_CASTRANKMASK          ((SWIG_CASTRANKLIMIT) -1)
#  define SWIG_CastRank(r)           (r & SWIG_CASTRANKMASK)
SWIGINTERNINLINE int SWIG_AddCast(int r) {
  return SWIG_IsOK(r) ? ((SWIG_CastRank(r) < SWIG_MAXCASTRANK) ? (r + 1) : SWIG_ERROR) : r;
}
SWIGINTERNINLINE int SWIG_CheckState(int r) {
  return SWIG_IsOK(r) ? SWIG_CastRank(r) + 1 : 0;
}
#else /* no cast-rank mode */
#  define SWIG_AddCast(r) (r)
#  define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#endif


#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *, int *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

/* Structure to store information on one type */
typedef struct swig_type_info {
  const char             *name;			/* mangled name of this type */
  const char             *str;			/* human readable name of this type */
  swig_dycast_func        dcast;		/* dynamic cast function down a hierarchy */
  struct swig_cast_info  *cast;			/* linked list of types that can cast into this type */
  void                   *clientdata;		/* language specific type data */
  int                    owndata;		/* flag if the structure owns the clientdata */
} swig_type_info;

/* Structure to store a type and conversion function used for casting */
typedef struct swig_cast_info {
  swig_type_info         *type;			/* pointer to type that is equivalent to this type */
  swig_converter_func     converter;		/* function to cast the void pointers */
  struct swig_cast_info  *next;			/* pointer to next cast in linked list */
  struct swig_cast_info  *prev;			/* pointer to the previous cast */
} swig_cast_info;

/* Structure used to store module information
 * Each module generates one structure like this, and the runtime collects
 * all of these structures and stores them in a circularly linked list.*/
typedef struct swig_module_info {
  swig_type_info         **types;		/* Array of pointers to swig_type_info structures that are in this module */
  size_t                 size;		        /* Number of types in this module */
  struct swig_module_info *next;		/* Pointer to next element in circularly linked list */
  swig_type_info         **type_initial;	/* Array of initially generated type structures */
  swig_cast_info         **cast_initial;	/* Array of initially generated casting structures */
  void                    *clientdata;		/* Language specific module data */
} swig_module_info;

/*
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return (*f1 > *f2) ? 1 : -1;
  }
  return (int)((l1 - f1) - (l2 - f2));
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if equal, -1 if nb < tb, 1 if nb > tb
*/
SWIGRUNTIME int
SWIG_TypeCmp(const char *nb, const char *tb) {
  int equiv = 1;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (equiv != 0 && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te);
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if not equal, 1 if equal
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  return SWIG_TypeCmp(nb, tb) == 0 ? 1 : 0;
}

/*
  Check the typename
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (strcmp(iter->type->name, c) == 0) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Identical to SWIG_TypeCheck, except strcmp is replaced with a pointer comparison
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheckStruct(swig_type_info *from, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (iter->type == from) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_cast_info *ty, void *ptr, int *newmemory) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr, newmemory);
}

/*
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (!type) return NULL;
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/*
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_cast_info *cast = ti->cast;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;

  while (cast) {
    if (!cast->converter) {
      swig_type_info *tc = cast->type;
      if (!tc->clientdata) {
	SWIG_TypeClientData(tc, clientdata);
      }
    }
    cast = cast->next;
  }
}
SWIGRUNTIME void
SWIG_TypeNewClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientData(ti, clientdata);
  ti->owndata = 1;
}

/*
  Search for a swig_type_info structure only by mangled name
  Search is a O(log #types)

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_MangledTypeQueryModule(swig_module_info *start,
                            swig_module_info *end,
		            const char *name) {
  swig_module_info *iter = start;
  do {
    if (iter->size) {
      size_t l = 0;
      size_t r = iter->size - 1;
      do {
	/* since l+r >= 0, we can (>> 1) instead (/ 2) */
	size_t i = (l + r) >> 1;
	const char *iname = iter->types[i]->name;
	if (iname) {
	  int compare = strcmp(name, iname);
	  if (compare == 0) {
	    return iter->types[i];
	  } else if (compare < 0) {
	    if (i) {
	      r = i - 1;
	    } else {
	      break;
	    }
	  } else if (compare > 0) {
	    l = i + 1;
	  }
	} else {
	  break; /* should never happen */
	}
      } while (l <= r);
    }
    iter = iter->next;
  } while (iter != end);
  return 0;
}

/*
  Search for a swig_type_info structure for either a mangled name or a human readable name.
  It first searches the mangled names of the types, which is a O(log #types)
  If a type is not found it then searches the human readable names, which is O(#types).

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryModule(swig_module_info *start,
                     swig_module_info *end,
		     const char *name) {
  /* STEP 1: Search the name field using binary search */
  swig_type_info *ret = SWIG_MangledTypeQueryModule(start, end, name);
  if (ret) {
    return ret;
  } else {
    /* STEP 2: If the type hasn't been found, do a complete search
       of the str field (the human readable name) */
    swig_module_info *iter = start;
    do {
      size_t i = 0;
      for (; i < iter->size; ++i) {
	if (iter->types[i]->str && (SWIG_TypeEquiv(iter->types[i]->str, name)))
	  return iter->types[i];
      }
      iter = iter->next;
    } while (iter != end);
  }

  /* neither found a match */
  return 0;
}

/*
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static const char hex[17] = "0123456789abcdef";
  const unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    unsigned char uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/*
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu = u + sz;
  for (; u != eu; ++u) {
    char d = *(c++);
    unsigned char uu;
    if ((d >= '0') && (d <= '9'))
      uu = (unsigned char)((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = (unsigned char)((d - ('a'-10)) << 4);
    else
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (unsigned char)(d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (unsigned char)(d - ('a'-10));
    else
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/*
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif

/* -----------------------------------------------------------------------------
 * phprun.swg
 *
 * PHP runtime library
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C" {
#endif
#include "zend.h"
#include "zend_API.h"
#include "zend_exceptions.h"
#include "php.h"

#if PHP_MAJOR_VERSION != 7
# error These bindings need PHP7 - to generate PHP5 bindings use: swig -php5
#endif

#include "ext/standard/php_string.h"
#include <stdlib.h> /* for abort(), used in generated code. */

/* This indirection is to work around const correctness issues in older PHP.
 * FIXME: Remove for PHP7?  Or might user code be using it? */
#define SWIG_ZEND_NAMED_FE(ZN, N, A) ZEND_NAMED_FE(ZN, N, A)

#define SWIG_BOOL_CONSTANT(N, V) REGISTER_BOOL_CONSTANT(#N, V, CONST_CS | CONST_PERSISTENT)
#define SWIG_LONG_CONSTANT(N, V) REGISTER_LONG_CONSTANT(#N, V, CONST_CS | CONST_PERSISTENT)
#define SWIG_DOUBLE_CONSTANT(N, V) REGISTER_DOUBLE_CONSTANT(#N, V, CONST_CS | CONST_PERSISTENT)
#define SWIG_STRING_CONSTANT(N, V) REGISTER_STRING_CONSTANT(#N, (char*)V, CONST_CS | CONST_PERSISTENT)
#define SWIG_CHAR_CONSTANT(N, V) do {\
    char swig_char = (V);\
    REGISTER_STRINGL_CONSTANT(#N, &swig_char, 1, CONST_CS | CONST_PERSISTENT);\
} while (0)

#ifdef __cplusplus
}
#endif

#define SWIG_fail goto fail

static const char *default_error_msg = "Unknown error occurred";
static int default_error_code = E_ERROR;

#define SWIG_PHP_Arg_Error_Msg(argnum,extramsg) "Error in argument " #argnum " "#extramsg

#define SWIG_PHP_Error(code,msg) do { SWIG_ErrorCode() = code; SWIG_ErrorMsg() = msg; SWIG_fail; } while (0)

#define SWIG_contract_assert(expr,msg) \
  if (!(expr) ) { zend_printf("Contract Assert Failed %s\n",msg ); } else

/* Standard SWIG API */
#define SWIG_GetModule(clientdata) SWIG_Php_GetModule()
#define SWIG_SetModule(clientdata, pointer) SWIG_Php_SetModule(pointer)

/* used to wrap returned objects in so we know whether they are newobject
   and need freeing, or not */
typedef struct {
  void * ptr;
  int newobject;
} swig_object_wrapper;

#define SWIG_as_voidptr(a) const_cast< void * >(static_cast< const void * >(a))

static void
SWIG_SetPointerZval(zval *z, void *ptr, swig_type_info *type, int newobject) {
  /*
   * First test for Null pointers.  Return those as PHP native NULL
   */
  if (!ptr ) {
    ZVAL_NULL(z);
    return;
  }
  if (type->clientdata) {
    swig_object_wrapper *value;
    if (! (*(int *)(type->clientdata)))
      zend_error(E_ERROR, "Type: %s failed to register with zend",type->name);
    value=(swig_object_wrapper *)emalloc(sizeof(swig_object_wrapper));
    value->ptr=ptr;
    value->newobject=(newobject & 1);
    if ((newobject & 2) == 0) {
      /* Just register the pointer as a resource. */
      ZVAL_RES(z, zend_register_resource(value, *(int *)(type->clientdata)));
    } else {
      /*
       * Wrap the resource in an object, the resource will be accessible
       * via the "_cPtr" member. This is currently only used by
       * directorin typemaps.
       */
      zval resource;
      zend_class_entry *ce = NULL;
      const char *type_name = type->name+3; /* +3 so: _p_Foo -> Foo */
      size_t type_name_len;
      const char * p;
      HashTable * ht;

      /* Namespace__Foo -> Foo */
      /* FIXME: ugly and goes wrong for classes with __ in their names. */
      while ((p = strstr(type_name, "__")) != NULL) {
        type_name = p + 2;
      }
      type_name_len = strlen(type_name);

      ZVAL_RES(&resource, zend_register_resource(value, *(int *)(type->clientdata)));
      if (SWIG_PREFIX_LEN > 0) {
        zend_string * classname = zend_string_alloc(SWIG_PREFIX_LEN + type_name_len, 0);
        memcpy(classname->val, SWIG_PREFIX, SWIG_PREFIX_LEN);
        memcpy(classname->val + SWIG_PREFIX_LEN, type_name, type_name_len);
        ce = zend_lookup_class(classname);
        zend_string_release(classname);
      } else {
        zend_string * classname = zend_string_init(type_name, type_name_len, 0);
        ce = zend_lookup_class(classname);
        zend_string_release(classname);
      }
      if (ce == NULL) {
        /* class does not exist */
        ce = zend_standard_class_def;
      }

      ALLOC_HASHTABLE(ht);
      zend_hash_init(ht, 1, NULL, NULL, 0);
      zend_hash_str_update(ht, "_cPtr", sizeof("_cPtr") - 1, &resource);
      object_and_properties_init(z, ce, ht);
    }
    return;
  }
  zend_error(E_ERROR, "Type: %s not registered with zend",type->name);
}

/* This pointer conversion routine takes the native pointer p (along with
   its type name) and converts it by calling appropriate casting functions
   according to ty.  The resultant pointer is returned, or NULL is returned
   if the pointer can't be cast.

   Sadly PHP has no API to find a type name from a type id, only from an
   instance of a resource of the type id, so we have to pass type_name as well.

   The two functions which might call this are:
   SWIG_ConvertResourcePtr which gets the type name from the resource
   and the registered zend destructors for which we have one per type each
   with the type name hard wired in. */
static void *
SWIG_ConvertResourceData(void * p, const char *type_name, swig_type_info *ty) {
  swig_cast_info *tc;
  void *result = 0;

  if (!ty) {
    /* They don't care about the target type, so just pass on the pointer! */
    return p;
  }

  if (! type_name) {  
    /* can't convert p to ptr type ty if we don't know what type p is */
    return NULL;
  }

  /* convert and cast p from type_name to ptr as ty. */
  tc = SWIG_TypeCheck(type_name, ty);
  if (tc) {
    int newmemory = 0;
    result = SWIG_TypeCast(tc, p, &newmemory);
    assert(!newmemory); /* newmemory handling not yet implemented */
  }
  return result;
}

/* This function returns a pointer of type ty by extracting the pointer
   and type info from the resource in z.  z must be a resource.
   If it fails, NULL is returned.
   It uses SWIG_ConvertResourceData to do the real work. */
static void *
SWIG_ConvertResourcePtr(zval *z, swig_type_info *ty, int flags) {
  swig_object_wrapper *value;
  void *p;
  const char *type_name;

  if (Z_RES_TYPE_P(z) == -1) return NULL;
  value = (swig_object_wrapper *) Z_RES_VAL_P(z);
  if (flags & SWIG_POINTER_DISOWN) {
    value->newobject = 0;
  }
  p = value->ptr;

  type_name=zend_rsrc_list_get_rsrc_type(Z_RES_P(z));

  return SWIG_ConvertResourceData(p, type_name, ty);
}

/* We allow passing of a RESOURCE pointing to the object or an OBJECT whose
   _cPtr is a resource pointing to the object */
static int
SWIG_ConvertPtr(zval *z, void **ptr, swig_type_info *ty, int flags) {
  if (z == NULL) {
    *ptr = 0;
    return 0;
  }

  switch (Z_TYPE_P(z)) {
    case IS_OBJECT: {
      HashTable * ht = Z_OBJ_HT_P(z)->get_properties(z);
      if (ht) {
        zval * _cPtr = zend_hash_str_find(ht, "_cPtr", sizeof("_cPtr") - 1);
        if (_cPtr) {
          if (Z_TYPE_P(_cPtr) == IS_INDIRECT) {
            _cPtr = Z_INDIRECT_P(_cPtr);
          }
          if (Z_TYPE_P(_cPtr) == IS_RESOURCE) {
            *ptr = SWIG_ConvertResourcePtr(_cPtr, ty, flags);
            return (*ptr == NULL ? -1 : 0);
          }
        }
      }
      break;
    }
    case IS_RESOURCE:
      *ptr = SWIG_ConvertResourcePtr(z, ty, flags);
      return (*ptr == NULL ? -1 : 0);
    case IS_NULL:
      *ptr = 0;
      return 0;
  }

  return -1;
}

static char const_name[] = "swig_runtime_data_type_pointer";
static swig_module_info *SWIG_Php_GetModule() {
  zval *pointer = zend_get_constant_str(const_name, sizeof(const_name) - 1);
  if (pointer) {
    if (Z_TYPE_P(pointer) == IS_LONG) {
      return (swig_module_info *) pointer->value.lval;
    }
  } 
  return NULL;
}

static void SWIG_Php_SetModule(swig_module_info *pointer) {
  REGISTER_MAIN_LONG_CONSTANT(const_name, (long) pointer, CONST_PERSISTENT | CONST_CS);
}


/* -------- TYPES TABLE (BEGIN) -------- */

#define SWIGTYPE_int swig_types[0]
#define SWIGTYPE_p_cppcms_capi_cookie swig_types[1]
#define SWIGTYPE_p_cppcms_capi_session swig_types[2]
#define SWIGTYPE_p_cppcms_capi_session_pool swig_types[3]
static swig_type_info *swig_types[5];
static swig_module_info swig_module = {swig_types, 4, 0, 0, 0, 0};
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)

/* -------- TYPES TABLE (END) -------- */

/* header section */
ZEND_BEGIN_MODULE_GLOBALS(cppcms_api)
const char *error_msg;
int error_code;
ZEND_END_MODULE_GLOBALS(cppcms_api)
ZEND_DECLARE_MODULE_GLOBALS(cppcms_api)
#define SWIG_ErrorMsg() (cppcms_api_globals.error_msg)
#define SWIG_ErrorCode() (cppcms_api_globals.error_code)
#ifdef __GNUC__
static void SWIG_FAIL(void) __attribute__ ((__noreturn__));
#endif

static void SWIG_FAIL(void) {
    zend_error(SWIG_ErrorCode(), "%s", SWIG_ErrorMsg());
    abort();
}

static void cppcms_api_init_globals(zend_cppcms_api_globals *globals ) {
  globals->error_msg = default_error_msg;
  globals->error_code = default_error_code;
}
static void SWIG_ResetError(void) {
  SWIG_ErrorMsg() = default_error_msg;
  SWIG_ErrorCode() = default_error_code;
}

ZEND_NAMED_FUNCTION(_wrap_swig_cppcms_api_alter_newobject) {
  zval args[2];
  swig_object_wrapper *value;

  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }

  value = (swig_object_wrapper *) Z_RES_VAL(args[0]);
  value->newobject = zval_is_true(&args[1]);

  return;
}
ZEND_NAMED_FUNCTION(_wrap_swig_cppcms_api_get_newobject) {
  zval args[1];
  swig_object_wrapper *value;

  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }

  value = (swig_object_wrapper *) Z_RES_VAL(args[0]);
  RETVAL_LONG(value->newobject);

  return;
}
#define SWIG_name  "cppcms_api"
#ifdef __cplusplus
extern "C" {
#endif
#include "php.h"
#include "php_ini.h"
#include "ext/standard/info.h"
#include "php_cppcms_api.h"
#ifdef __cplusplus
}
#endif


#include <cppcms/capi/session.h>

SWIGINTERN struct cppcms_capi_session_pool *new_cppcms_capi_session_pool(void){ return cppcms_capi_session_pool_new(); }
SWIGINTERN void delete_cppcms_capi_session_pool(struct cppcms_capi_session_pool *self){ return cppcms_capi_session_pool_delete(self); }
SWIGINTERN int cppcms_capi_session_pool_error(struct cppcms_capi_session_pool *self){ return cppcms_capi_error(self); }
SWIGINTERN char const *cppcms_capi_session_pool_error_message(struct cppcms_capi_session_pool *self){ return cppcms_capi_error_message(self); }
SWIGINTERN char const *cppcms_capi_session_pool_error_clear(struct cppcms_capi_session_pool *self){ return cppcms_capi_error_clear(self); }
SWIGINTERN struct cppcms_capi_session *new_cppcms_capi_session(void){ return cppcms_capi_session_new(); }
SWIGINTERN void delete_cppcms_capi_session(struct cppcms_capi_session *self){ return cppcms_capi_session_delete(self); }
SWIGINTERN int cppcms_capi_session_error(struct cppcms_capi_session *self){ return cppcms_capi_error(self); }
SWIGINTERN char const *cppcms_capi_session_error_message(struct cppcms_capi_session *self){ return cppcms_capi_error_message(self); }
SWIGINTERN char const *cppcms_capi_session_error_clear(struct cppcms_capi_session *self){ return cppcms_capi_error_clear(self); }
SWIGINTERN struct cppcms_capi_cookie *new_cppcms_capi_cookie(void){ return NULL; }
SWIGINTERN void delete_cppcms_capi_cookie(struct cppcms_capi_cookie *self){ cppcms_capi_cookie_delete(self); }

/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__int = {"_int", "int", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_cppcms_capi_cookie = {"_p_cppcms_capi_cookie", "struct cppcms_capi_cookie *|cppcms_capi_cookie *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_cppcms_capi_session = {"_p_cppcms_capi_session", "struct cppcms_capi_session *|cppcms_capi_session *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_cppcms_capi_session_pool = {"_p_cppcms_capi_session_pool", "struct cppcms_capi_session_pool *|cppcms_capi_session_pool *", 0, 0, (void*)0, 0};

static swig_type_info *swig_type_initial[] = {
  &_swigt__int,
  &_swigt__p_cppcms_capi_cookie,
  &_swigt__p_cppcms_capi_session,
  &_swigt__p_cppcms_capi_session_pool,
};

static swig_cast_info _swigc__int[] = {  {&_swigt__int, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_cppcms_capi_cookie[] = {  {&_swigt__p_cppcms_capi_cookie, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_cppcms_capi_session[] = {  {&_swigt__p_cppcms_capi_session, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_cppcms_capi_session_pool[] = {  {&_swigt__p_cppcms_capi_session_pool, 0, 0, 0},{0, 0, 0, 0}};

static swig_cast_info *swig_cast_initial[] = {
  _swigc__int,
  _swigc__p_cppcms_capi_cookie,
  _swigc__p_cppcms_capi_session,
  _swigc__p_cppcms_capi_session_pool,
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

/* end header section */
/* vdecl subsection */
static int le_swig__int=0; /* handle for _int */
static int le_swig__p_cppcms_capi_cookie=0; /* handle for CppCMSAPICookie */
static int le_swig__p_cppcms_capi_session=0; /* handle for CppCMSAPISession */
static int le_swig__p_cppcms_capi_session_pool=0; /* handle for CppCMSAPIPool */
/* end vdecl subsection */
/* wrapper section */
ZEND_NAMED_FUNCTION(_wrap_new_CppCMSAPIPool) {
  struct cppcms_capi_session_pool *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 0) {
    WRONG_PARAM_COUNT;
  }
  
  result = (struct cppcms_capi_session_pool *)new_cppcms_capi_session_pool();
  
  SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_cppcms_capi_session_pool, 1);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


/* This function is designed to be called by the zend list destructors */
/* to typecast and do the actual destruction */
static void __wrap_delete_CppCMSAPIPool(zend_resource *res, const char *type_name) {
  swig_object_wrapper *value=(swig_object_wrapper *) res->ptr ;
  void *ptr=value->ptr ;
  int newobject=value->newobject ;
  struct cppcms_capi_session_pool *arg1 = (struct cppcms_capi_session_pool *) 0 ;
  
  efree(value);
  if (! newobject) return; /* can't delete it! */
  arg1 = (struct cppcms_capi_session_pool *)SWIG_ConvertResourceData(ptr, type_name, SWIGTYPE_p_cppcms_capi_session_pool);
  if (! arg1) zend_error(E_ERROR, "cppcms_capi_session_pool resource already free'd");
  delete_cppcms_capi_session_pool(arg1);
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPIPool_error) {
  struct cppcms_capi_session_pool *arg1 = (struct cppcms_capi_session_pool *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session_pool, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPIPool_error. Expected SWIGTYPE_p_cppcms_capi_session_pool");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_pool_error(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPIPool_error_message) {
  struct cppcms_capi_session_pool *arg1 = (struct cppcms_capi_session_pool *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session_pool, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPIPool_error_message. Expected SWIGTYPE_p_cppcms_capi_session_pool");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_session_pool_error_message(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPIPool_error_clear) {
  struct cppcms_capi_session_pool *arg1 = (struct cppcms_capi_session_pool *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session_pool, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPIPool_error_clear. Expected SWIGTYPE_p_cppcms_capi_session_pool");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_session_pool_error_clear(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPIPool_init) {
  struct cppcms_capi_session_pool *arg1 = (struct cppcms_capi_session_pool *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session_pool, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPIPool_init. Expected SWIGTYPE_p_cppcms_capi_session_pool");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_pool_init(arg1,(char const *)arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPIPool_init_from_json) {
  struct cppcms_capi_session_pool *arg1 = (struct cppcms_capi_session_pool *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session_pool, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPIPool_init_from_json. Expected SWIGTYPE_p_cppcms_capi_session_pool");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_pool_init_from_json(arg1,(char const *)arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_new_CppCMSAPISession) {
  struct cppcms_capi_session *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 0) {
    WRONG_PARAM_COUNT;
  }
  
  result = (struct cppcms_capi_session *)new_cppcms_capi_session();
  
  SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_cppcms_capi_session, 1);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


/* This function is designed to be called by the zend list destructors */
/* to typecast and do the actual destruction */
static void __wrap_delete_CppCMSAPISession(zend_resource *res, const char *type_name) {
  swig_object_wrapper *value=(swig_object_wrapper *) res->ptr ;
  void *ptr=value->ptr ;
  int newobject=value->newobject ;
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  
  efree(value);
  if (! newobject) return; /* can't delete it! */
  arg1 = (struct cppcms_capi_session *)SWIG_ConvertResourceData(ptr, type_name, SWIGTYPE_p_cppcms_capi_session);
  if (! arg1) zend_error(E_ERROR, "cppcms_capi_session resource already free'd");
  delete_cppcms_capi_session(arg1);
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_error) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_error. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_error(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_error_message) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_error_message. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_session_error_message(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_error_clear) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_error_clear. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_session_error_clear(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_init) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  cppcms_capi_session_pool *arg2 = (cppcms_capi_session_pool *) 0 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_init. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  if (SWIG_ConvertPtr(&args[1], (void **) &arg2, SWIGTYPE_p_cppcms_capi_session_pool, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 2 of CppCMSAPISession_init. Expected SWIGTYPE_p_cppcms_capi_session_pool");
  }
  
  result = (int)cppcms_capi_session_init(arg1,arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_clear) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_clear. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_clear(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_is_set) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_is_set. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_is_set(arg1,(char const *)arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_erase) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_erase. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_erase(arg1,(char const *)arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_exposed) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get_exposed. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_get_exposed(arg1,(char const *)arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_exposed) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  zval args[3];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 3 || zend_get_parameters_array_ex(3, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_set_exposed. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,6,CONVERT_INT_IN@*/
  arg3 = (int) zval_get_long(&args[2]);
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_set_exposed(arg1,(char const *)arg2,arg3);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_first_key) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get_first_key. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_session_get_first_key(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_next_key) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get_next_key. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_session_get_next_key(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_csrf_token) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get_csrf_token. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_session_get_csrf_token(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  zval args[3];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 3 || zend_get_parameters_array_ex(3, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_set. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[2])) {
    arg3 = (char *) 0;
  } else {
    convert_to_string(&args[2]);
    arg3 = (char *) Z_STRVAL(args[2]);
  }
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_set(arg1,(char const *)arg2,(char const *)arg3);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (char *)cppcms_capi_session_get(arg1,(char const *)arg2);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_binary_as_hex) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  zval args[3];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 3 || zend_get_parameters_array_ex(3, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_set_binary_as_hex. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[2])) {
    arg3 = (char *) 0;
  } else {
    convert_to_string(&args[2]);
    arg3 = (char *) Z_STRVAL(args[2]);
  }
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_set_binary_as_hex(arg1,(char const *)arg2,(char const *)arg3);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_binary_as_hex) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get_binary_as_hex. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (char *)cppcms_capi_session_get_binary_as_hex(arg1,(char const *)arg2);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_binary_len) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get_binary_len. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_get_binary_len(arg1,(char const *)arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_reset_session) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_reset_session. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_reset_session(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_default_age) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_set_default_age. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_set_default_age(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_age) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  int arg2 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_set_age. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,6,CONVERT_INT_IN@*/
  arg2 = (int) zval_get_long(&args[1]);
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_set_age(arg1,arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_age) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get_age. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_get_age(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_default_expiration) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_set_default_expiration. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_set_default_expiration(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_expiration) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  int arg2 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_set_expiration. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,6,CONVERT_INT_IN@*/
  arg2 = (int) zval_get_long(&args[1]);
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_set_expiration(arg1,arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_expiration) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get_expiration. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_get_expiration(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_on_server) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  int arg2 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_set_on_server. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,6,CONVERT_INT_IN@*/
  arg2 = (int) zval_get_long(&args[1]);
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_set_on_server(arg1,arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_on_server) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get_on_server. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_get_on_server(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_get_session_cookie_name) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_get_session_cookie_name. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_session_get_session_cookie_name(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_add_cookie_name) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_add_cookie_name. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_add_cookie_name(arg1,(char const *)arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_set_session_cookie) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  char *arg2 = (char *) 0 ;
  zval args[2];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 2 || zend_get_parameters_array_ex(2, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_set_session_cookie. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  
  /*@SWIG:/opt/swig-3.0.12/share/swig/3.0.12/php/utils.i,57,CONVERT_STRING_IN@*/
  if (Z_ISNULL(args[1])) {
    arg2 = (char *) 0;
  } else {
    convert_to_string(&args[1]);
    arg2 = (char *) Z_STRVAL(args[1]);
  }
  /*@SWIG@*/;
  
  result = (int)cppcms_capi_session_set_session_cookie(arg1,(char const *)arg2);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_load) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_load. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_load(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_save) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_save. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_session_save(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_cookie_first) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  cppcms_capi_cookie *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_cookie_first. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (cppcms_capi_cookie *)cppcms_capi_session_cookie_first(arg1);
  
  SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_cppcms_capi_cookie, 1);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPISession_cookie_next) {
  struct cppcms_capi_session *arg1 = (struct cppcms_capi_session *) 0 ;
  zval args[1];
  cppcms_capi_cookie *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_session, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPISession_cookie_next. Expected SWIGTYPE_p_cppcms_capi_session");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (cppcms_capi_cookie *)cppcms_capi_session_cookie_next(arg1);
  
  SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_cppcms_capi_cookie, 1);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_new_CppCMSAPICookie) {
  struct cppcms_capi_cookie *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 0) {
    WRONG_PARAM_COUNT;
  }
  
  result = (struct cppcms_capi_cookie *)new_cppcms_capi_cookie();
  
  SWIG_SetPointerZval(return_value, (void *)result, SWIGTYPE_p_cppcms_capi_cookie, 1);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


/* This function is designed to be called by the zend list destructors */
/* to typecast and do the actual destruction */
static void __wrap_delete_CppCMSAPICookie(zend_resource *res, const char *type_name) {
  swig_object_wrapper *value=(swig_object_wrapper *) res->ptr ;
  void *ptr=value->ptr ;
  int newobject=value->newobject ;
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  
  efree(value);
  if (! newobject) return; /* can't delete it! */
  arg1 = (struct cppcms_capi_cookie *)SWIG_ConvertResourceData(ptr, type_name, SWIGTYPE_p_cppcms_capi_cookie);
  if (! arg1) zend_error(E_ERROR, "cppcms_capi_cookie resource already free'd");
  delete_cppcms_capi_cookie(arg1);
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_header) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_header. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_cookie_header(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_header_content) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_header_content. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_cookie_header_content(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_name) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_name. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_cookie_name(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_value) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_value. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_cookie_value(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_path) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_path. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_cookie_path(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_domain) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  char *result = 0 ;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_domain. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (char *)cppcms_capi_cookie_domain(arg1);
  
  if (!result) {
    RETVAL_NULL();
  } else {
    RETVAL_STRING((const char *)result);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_max_age_defined) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_max_age_defined. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_cookie_max_age_defined(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_max_age) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  unsigned int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_max_age. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (unsigned int)cppcms_capi_cookie_max_age(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_expires_defined) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_expires_defined. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_cookie_expires_defined(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_expires) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  long long result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_expires. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (long long)cppcms_capi_cookie_expires(arg1);
  
  if ((long long)LONG_MIN <= result && result <= (long long)LONG_MAX) {
    RETVAL_LONG((long)(result));
  } else {
    char temp[256];
    sprintf(temp, "%lld", (long long)result);
    RETVAL_STRING(temp);
  }
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


ZEND_NAMED_FUNCTION(_wrap_CppCMSAPICookie_is_secure) {
  struct cppcms_capi_cookie *arg1 = (struct cppcms_capi_cookie *) 0 ;
  zval args[1];
  int result;
  
  SWIG_ResetError();
  if(ZEND_NUM_ARGS() != 1 || zend_get_parameters_array_ex(1, args) != SUCCESS) {
    WRONG_PARAM_COUNT;
  }
  
  
  if (SWIG_ConvertPtr(&args[0], (void **) &arg1, SWIGTYPE_p_cppcms_capi_cookie, 0) < 0) {
    SWIG_PHP_Error(E_ERROR, "Type error in argument 1 of CppCMSAPICookie_is_secure. Expected SWIGTYPE_p_cppcms_capi_cookie");
  }
  
  if(!arg1) SWIG_PHP_Error(E_ERROR, "this pointer is NULL");
  result = (int)cppcms_capi_cookie_is_secure(arg1);
  
  RETVAL_LONG(result);
  
thrown:
  return;
fail:
  SWIG_FAIL();
}


static ZEND_RSRC_DTOR_FUNC(_swig_default_rsrc_destroy) {
  efree(res->ptr);
}
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_cppcms_capi_cookie) {
  __wrap_delete_CppCMSAPICookie(res, SWIGTYPE_p_cppcms_capi_cookie->name);
}
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_cppcms_capi_session) {
  __wrap_delete_CppCMSAPISession(res, SWIGTYPE_p_cppcms_capi_session->name);
}
static ZEND_RSRC_DTOR_FUNC(_wrap_destroy_p_cppcms_capi_session_pool) {
  __wrap_delete_CppCMSAPIPool(res, SWIGTYPE_p_cppcms_capi_session_pool->name);
}
/* end wrapper section */
/* class entry subsection */


/* arginfo subsection */
ZEND_BEGIN_ARG_INFO_EX(swig_arginfo_, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(swig_arginfo_0, 0, 0, 0)
 ZEND_ARG_PASS_INFO(0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(swig_arginfo_00, 0, 0, 0)
 ZEND_ARG_PASS_INFO(0)
 ZEND_ARG_PASS_INFO(0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(swig_arginfo_000, 0, 0, 0)
 ZEND_ARG_PASS_INFO(0)
 ZEND_ARG_PASS_INFO(0)
 ZEND_ARG_PASS_INFO(0)
ZEND_END_ARG_INFO()


/* entry subsection */
/* Every non-class user visible function must have an entry here */
static zend_function_entry cppcms_api_functions[] = {
 SWIG_ZEND_NAMED_FE(new_cppcmsapipool,_wrap_new_CppCMSAPIPool,swig_arginfo_)
 SWIG_ZEND_NAMED_FE(cppcmsapipool_error,_wrap_CppCMSAPIPool_error,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapipool_error_message,_wrap_CppCMSAPIPool_error_message,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapipool_error_clear,_wrap_CppCMSAPIPool_error_clear,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapipool_init,_wrap_CppCMSAPIPool_init,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapipool_init_from_json,_wrap_CppCMSAPIPool_init_from_json,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(new_cppcmsapisession,_wrap_new_CppCMSAPISession,swig_arginfo_)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_error,_wrap_CppCMSAPISession_error,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_error_message,_wrap_CppCMSAPISession_error_message,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_error_clear,_wrap_CppCMSAPISession_error_clear,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_init,_wrap_CppCMSAPISession_init,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_clear,_wrap_CppCMSAPISession_clear,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_is_set,_wrap_CppCMSAPISession_is_set,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_erase,_wrap_CppCMSAPISession_erase,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get_exposed,_wrap_CppCMSAPISession_get_exposed,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_set_exposed,_wrap_CppCMSAPISession_set_exposed,swig_arginfo_000)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get_first_key,_wrap_CppCMSAPISession_get_first_key,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get_next_key,_wrap_CppCMSAPISession_get_next_key,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get_csrf_token,_wrap_CppCMSAPISession_get_csrf_token,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_set,_wrap_CppCMSAPISession_set,swig_arginfo_000)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get,_wrap_CppCMSAPISession_get,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_set_binary_as_hex,_wrap_CppCMSAPISession_set_binary_as_hex,swig_arginfo_000)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get_binary_as_hex,_wrap_CppCMSAPISession_get_binary_as_hex,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get_binary_len,_wrap_CppCMSAPISession_get_binary_len,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_reset_session,_wrap_CppCMSAPISession_reset_session,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_set_default_age,_wrap_CppCMSAPISession_set_default_age,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_set_age,_wrap_CppCMSAPISession_set_age,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get_age,_wrap_CppCMSAPISession_get_age,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_set_default_expiration,_wrap_CppCMSAPISession_set_default_expiration,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_set_expiration,_wrap_CppCMSAPISession_set_expiration,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get_expiration,_wrap_CppCMSAPISession_get_expiration,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_set_on_server,_wrap_CppCMSAPISession_set_on_server,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get_on_server,_wrap_CppCMSAPISession_get_on_server,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_get_session_cookie_name,_wrap_CppCMSAPISession_get_session_cookie_name,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_add_cookie_name,_wrap_CppCMSAPISession_add_cookie_name,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_set_session_cookie,_wrap_CppCMSAPISession_set_session_cookie,swig_arginfo_00)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_load,_wrap_CppCMSAPISession_load,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_save,_wrap_CppCMSAPISession_save,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_cookie_first,_wrap_CppCMSAPISession_cookie_first,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapisession_cookie_next,_wrap_CppCMSAPISession_cookie_next,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(new_cppcmsapicookie,_wrap_new_CppCMSAPICookie,swig_arginfo_)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_header,_wrap_CppCMSAPICookie_header,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_header_content,_wrap_CppCMSAPICookie_header_content,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_name,_wrap_CppCMSAPICookie_name,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_value,_wrap_CppCMSAPICookie_value,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_path,_wrap_CppCMSAPICookie_path,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_domain,_wrap_CppCMSAPICookie_domain,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_max_age_defined,_wrap_CppCMSAPICookie_max_age_defined,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_max_age,_wrap_CppCMSAPICookie_max_age,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_expires_defined,_wrap_CppCMSAPICookie_expires_defined,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_expires,_wrap_CppCMSAPICookie_expires,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(cppcmsapicookie_is_secure,_wrap_CppCMSAPICookie_is_secure,swig_arginfo_0)
 SWIG_ZEND_NAMED_FE(swig_cppcms_api_alter_newobject,_wrap_swig_cppcms_api_alter_newobject,NULL)
 SWIG_ZEND_NAMED_FE(swig_cppcms_api_get_newobject,_wrap_swig_cppcms_api_get_newobject,NULL)
 ZEND_FE_END
};

/* init section */
zend_module_entry cppcms_api_module_entry = {
    STANDARD_MODULE_HEADER,
    "cppcms_api",
    cppcms_api_functions,
    PHP_MINIT(cppcms_api),
    NULL, /* No MSHUTDOWN code */
    NULL, /* No RINIT code */
    NULL, /* No RSHUTDOWN code */
    NULL, /* No MINFO code */
    NO_VERSION_YET,
    STANDARD_MODULE_PROPERTIES
};
zend_module_entry* SWIG_module_entry = &cppcms_api_module_entry;

#ifdef __cplusplus
extern "C" {
#endif
SWIGEXPORT zend_module_entry *get_module(void) { return &cppcms_api_module_entry; }
#ifdef __cplusplus
}
#endif

#define SWIG_php_minit PHP_MINIT_FUNCTION(cppcms_api)

/* -----------------------------------------------------------------------------
 * Type initialization:
 * This problem is tough by the requirement that no dynamic
 * memory is used. Also, since swig_type_info structures store pointers to
 * swig_cast_info structures and swig_cast_info structures store pointers back
 * to swig_type_info structures, we need some lookup code at initialization.
 * The idea is that swig generates all the structures that are needed.
 * The runtime then collects these partially filled structures.
 * The SWIG_InitializeModule function takes these initial arrays out of
 * swig_module, and does all the lookup, filling in the swig_module.types
 * array with the correct data and linking the correct swig_cast_info
 * structures together.
 *
 * The generated swig_type_info structures are assigned statically to an initial
 * array. We just loop through that array, and handle each type individually.
 * First we lookup if this type has been already loaded, and if so, use the
 * loaded structure instead of the generated one. Then we have to fill in the
 * cast linked list. The cast data is initially stored in something like a
 * two-dimensional array. Each row corresponds to a type (there are the same
 * number of rows as there are in the swig_type_initial array). Each entry in
 * a column is one of the swig_cast_info structures for that type.
 * The cast_initial array is actually an array of arrays, because each row has
 * a variable number of columns. So to actually build the cast linked list,
 * we find the array of casts associated with the type, and loop through it
 * adding the casts to the list. The one last trick we need to do is making
 * sure the type pointer in the swig_cast_info struct is correct.
 *
 * First off, we lookup the cast->type name to see if it is already loaded.
 * There are three cases to handle:
 *  1) If the cast->type has already been loaded AND the type we are adding
 *     casting info to has not been loaded (it is in this module), THEN we
 *     replace the cast->type pointer with the type pointer that has already
 *     been loaded.
 *  2) If BOTH types (the one we are adding casting info to, and the
 *     cast->type) are loaded, THEN the cast info has already been loaded by
 *     the previous module so we just ignore it.
 *  3) Finally, if cast->type has not already been loaded, then we add that
 *     swig_cast_info to the linked list (because the cast->type) pointer will
 *     be correct.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C" {
#if 0
} /* c-mode */
#endif
#endif

#if 0
#define SWIGRUNTIME_DEBUG
#endif


SWIGRUNTIME void
SWIG_InitializeModule(void *clientdata) {
  size_t i;
  swig_module_info *module_head, *iter;
  int init;

  /* check to see if the circular list has been setup, if not, set it up */
  if (swig_module.next==0) {
    /* Initialize the swig_module */
    swig_module.type_initial = swig_type_initial;
    swig_module.cast_initial = swig_cast_initial;
    swig_module.next = &swig_module;
    init = 1;
  } else {
    init = 0;
  }

  /* Try and load any already created modules */
  module_head = SWIG_GetModule(clientdata);
  if (!module_head) {
    /* This is the first module loaded for this interpreter */
    /* so set the swig module into the interpreter */
    SWIG_SetModule(clientdata, &swig_module);
  } else {
    /* the interpreter has loaded a SWIG module, but has it loaded this one? */
    iter=module_head;
    do {
      if (iter==&swig_module) {
        /* Our module is already in the list, so there's nothing more to do. */
        return;
      }
      iter=iter->next;
    } while (iter!= module_head);

    /* otherwise we must add our module into the list */
    swig_module.next = module_head->next;
    module_head->next = &swig_module;
  }

  /* When multiple interpreters are used, a module could have already been initialized in
     a different interpreter, but not yet have a pointer in this interpreter.
     In this case, we do not want to continue adding types... everything should be
     set up already */
  if (init == 0) return;

  /* Now work on filling in swig_module.types */
#ifdef SWIGRUNTIME_DEBUG
  printf("SWIG_InitializeModule: size %d\n", swig_module.size);
#endif
  for (i = 0; i < swig_module.size; ++i) {
    swig_type_info *type = 0;
    swig_type_info *ret;
    swig_cast_info *cast;

#ifdef SWIGRUNTIME_DEBUG
    printf("SWIG_InitializeModule: type %d %s\n", i, swig_module.type_initial[i]->name);
#endif

    /* if there is another module already loaded */
    if (swig_module.next != &swig_module) {
      type = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, swig_module.type_initial[i]->name);
    }
    if (type) {
      /* Overwrite clientdata field */
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found type %s\n", type->name);
#endif
      if (swig_module.type_initial[i]->clientdata) {
	type->clientdata = swig_module.type_initial[i]->clientdata;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found and overwrite type %s \n", type->name);
#endif
      }
    } else {
      type = swig_module.type_initial[i];
    }

    /* Insert casting types */
    cast = swig_module.cast_initial[i];
    while (cast->type) {

      /* Don't need to add information already in the list */
      ret = 0;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: look cast %s\n", cast->type->name);
#endif
      if (swig_module.next != &swig_module) {
        ret = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, cast->type->name);
#ifdef SWIGRUNTIME_DEBUG
	if (ret) printf("SWIG_InitializeModule: found cast %s\n", ret->name);
#endif
      }
      if (ret) {
	if (type == swig_module.type_initial[i]) {
#ifdef SWIGRUNTIME_DEBUG
	  printf("SWIG_InitializeModule: skip old type %s\n", ret->name);
#endif
	  cast->type = ret;
	  ret = 0;
	} else {
	  /* Check for casting already in the list */
	  swig_cast_info *ocast = SWIG_TypeCheck(ret->name, type);
#ifdef SWIGRUNTIME_DEBUG
	  if (ocast) printf("SWIG_InitializeModule: skip old cast %s\n", ret->name);
#endif
	  if (!ocast) ret = 0;
	}
      }

      if (!ret) {
#ifdef SWIGRUNTIME_DEBUG
	printf("SWIG_InitializeModule: adding cast %s\n", cast->type->name);
#endif
        if (type->cast) {
          type->cast->prev = cast;
          cast->next = type->cast;
        }
        type->cast = cast;
      }
      cast++;
    }
    /* Set entry in modules->types array equal to the type */
    swig_module.types[i] = type;
  }
  swig_module.types[i] = 0;

#ifdef SWIGRUNTIME_DEBUG
  printf("**** SWIG_InitializeModule: Cast List ******\n");
  for (i = 0; i < swig_module.size; ++i) {
    int j = 0;
    swig_cast_info *cast = swig_module.cast_initial[i];
    printf("SWIG_InitializeModule: type %d %s\n", i, swig_module.type_initial[i]->name);
    while (cast->type) {
      printf("SWIG_InitializeModule: cast type %s\n", cast->type->name);
      cast++;
      ++j;
    }
  printf("---- Total casts: %d\n",j);
  }
  printf("**** SWIG_InitializeModule: Cast List ******\n");
#endif
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientData(void) {
  size_t i;
  swig_cast_info *equiv;
  static int init_run = 0;

  if (init_run) return;
  init_run = 1;

  for (i = 0; i < swig_module.size; i++) {
    if (swig_module.types[i]->clientdata) {
      equiv = swig_module.types[i]->cast;
      while (equiv) {
        if (!equiv->converter) {
          if (equiv->type && !equiv->type->clientdata)
            SWIG_TypeClientData(equiv->type, swig_module.types[i]->clientdata);
        }
        equiv = equiv->next;
      }
    }
  }
}

#ifdef __cplusplus
#if 0
{ /* c-mode */
#endif
}
#endif


SWIG_php_minit {
    SWIG_InitializeModule(0);

/* oinit subsection */
ZEND_INIT_MODULE_GLOBALS(cppcms_api, cppcms_api_init_globals, NULL);

/* Register resource destructors for pointer types */
le_swig__int=zend_register_list_destructors_ex(_swig_default_rsrc_destroy, NULL, SWIGTYPE_int->name, module_number);
SWIG_TypeClientData(SWIGTYPE_int,&le_swig__int);
le_swig__p_cppcms_capi_cookie=zend_register_list_destructors_ex(_wrap_destroy_p_cppcms_capi_cookie, NULL, SWIGTYPE_p_cppcms_capi_cookie->name, module_number);
SWIG_TypeClientData(SWIGTYPE_p_cppcms_capi_cookie,&le_swig__p_cppcms_capi_cookie);
le_swig__p_cppcms_capi_session=zend_register_list_destructors_ex(_wrap_destroy_p_cppcms_capi_session, NULL, SWIGTYPE_p_cppcms_capi_session->name, module_number);
SWIG_TypeClientData(SWIGTYPE_p_cppcms_capi_session,&le_swig__p_cppcms_capi_session);
le_swig__p_cppcms_capi_session_pool=zend_register_list_destructors_ex(_wrap_destroy_p_cppcms_capi_session_pool, NULL, SWIGTYPE_p_cppcms_capi_session_pool->name, module_number);
SWIG_TypeClientData(SWIGTYPE_p_cppcms_capi_session_pool,&le_swig__p_cppcms_capi_session_pool);
CG(active_class_entry) = NULL;
/* end oinit subsection */

/* cinit subsection */
SWIG_LONG_CONSTANT(SESSION_FIXED, (int)0);
SWIG_LONG_CONSTANT(SESSION_RENEW, (int)1);
SWIG_LONG_CONSTANT(SESSION_BROWSER, (int)2);
SWIG_LONG_CONSTANT(ERROR_OK, (int)0);
SWIG_LONG_CONSTANT(ERROR_GENERAL, (int)1);
SWIG_LONG_CONSTANT(ERROR_RUNTIME, (int)2);
SWIG_LONG_CONSTANT(ERROR_INVALID_ARGUMENT, (int)4);
SWIG_LONG_CONSTANT(ERROR_LOGIC, (int)5);
SWIG_LONG_CONSTANT(ERROR_ALLOC, (int)6);
/* end cinit subsection */

    return SUCCESS;
}

/* end init section */
